### ISSUE TITLE
스토리 초반부

### ISSUE THREAD

**Issue by b1uedwarf** [YeonduBori/Media_Velocity#2]
#스토리 초반
시한부 판정을 받은 주인공. 혼자 여행을 다니다 밤중에 길을 잃는다. 정처없이 걷던 중 갑자기 들리는 피아노 소리를 따라 들어가보니 숲속에 피아노와 함께 공터가 있다. 피아노를 치고있는 ???는 ....

**Comment by YeonduBori** [comment]
@b1uedwarf 시범 태그

**Comment by b1uedwarf** [comment]
엎었습니다

**Comment by YeonduBori** [comment]
그럼 Close Issue 해주시면 됩니다 @b1uedwarf
