### ISSUE TITLE
ㅎㅎ

### ISSUE THREAD

**Issue by naaaaxx** [YeonduBori/Media_Velocity#3]
테스트용

**Comment by YeonduBori** [comment]
@naaaaxx  매우 좋습니다 좋아요 시범 태그로 한번 태그해봤습니다.

**Comment by naaaaxx** [comment]
> @naaaaxx 매우 좋습니다 좋아요 시범 태그로 한번 태그해봤습니다.

ㅇㅣ메일 제대로 왔어요!
